services:
  train:
    build: .
    image: anime-face-classification:latest
    container_name: anime-face-train
    command: python main.py
    volumes:
      - ./outputs:/app/outputs
      - ./src/data/extracted:/app/src/data/extracted
    environment:
      PYTHONUNBUFFERED: "1"
      MPLBACKEND: Agg
      SHOW_FIGURES: "0"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    shm_size: "2gb"
    gpus: all
    tty: true
